### PR TITLE
Add YandexWeather Usermod

### PR DESCRIPTION
**Pull request by 2Grey**
Add V2 Usermod for getting weather data from [Yandex Weather](https://yandex.ru/pogoda) service.

### Features
- Displays weather on the Info page
- Post weather to MQTT

### CODE REVIEW

**Comment by ewoudwijma** [comment]
Cool! We have also the weather usermod. Using openweather. Did you look into that? Maybe we could merge this into this usermod. It also displays weather bars on a 2D display

**Comment by 2Grey** [comment]
There are some differences in APIs, which, it seems to me, prevents us from unifying solutions and creating a common interface (protocol) for them.

#### Differences
| Feature | Yandex | OpenWeather |
|:--------|:-------|:------------|
| **Units** | Celsius | All |
| **Forecast** | Next two parts of day | Next 5 days (3 hours step) |
---
Units isn't a problem, i can convert Celsius to other ones.
But difference of forecast is huge.

**Comment by ewoudwijma** [comment]
Okay, still would be nice if in some way we could unify it. But for now I merge your pull request and we first start playing with it ;-)
Thx for contributing !
Kind regards
Ewoud

**Comment by dosipod** [comment]
@2Grey Is https://yandex.ru/pogoda/ only in  Russian ? 
I was able to compile it and create a user with yandex but lost in the site trying to get the api key

**Comment by 2Grey** [comment]
> @2Grey Is https://yandex.ru/pogoda/ only in Russian ? I was able to compile it and create a user with yandex but lost in the site trying to get the api key

As far as I understand the documentation is only in Russian, but there is English for the Developer's Account

API Documentation: [Original](https://yandex.ru/dev/weather/doc/dg/concepts/about.html) | [Translated](https://yandex-ru.translate.goog/dev/weather/doc/dg/concepts/about.html?_x_tr_sl=ru&_x_tr_tl=en)

[Developer's Account](https://developer.tech.yandex.ru/services)

If the account page is in Russian, click on the Russian flag at the bottom of the page and select your preferred language

**Pull request merged**
