### PR TITLE
T7-S3 (LILYGO / TTGO) with MOONHUB

### PR DESCRIPTION
**Pull request by softhack007**
build env and HUB75 pinout for S3 and MOONHUB HUB75 adapter board

### CODE REVIEW

**Comment by dosipod** [comment]
MOONHUB HUB75 adapter board ? What and where is that

**Comment by softhack007** [comment]
> MOONHUB HUB75 adapter board ? What and where is that

@dosipod Its latest-greatest - a small HUB75 adapter board, similar to the "forum" board but designed for S3 with PSRAM - especially the T7-S3.

@lost-hope is making the design, so he's the one to ask for more info. It's a cool little board 😃 the biggest investment is the T7-S3. 

Here is a teaser

Screenshot_20241105-145045_Snapseed
Screenshot_20241105-144912_Gallery

**Comment by lost-hope** [comment]
As Frank said, 
it is a small passive adapter board for an ESP32 S3 with octal PSRAM (which is quite fast)
But it is still in development. First version (the one Frank and some others have) had a missing pin, which is fixed in the second version. 
Will release the files when it is done in a repository.
Maybe Frank/Ewoud have made boards available in their tindie Store , though i think that it wont be worth it;D
Since it is a passive board, it is just a bare PCB, so very cheap.

**Comment by dosipod** [comment]
I see T7-S3 on aliepress so that is good and a PCB to reduce the wiring even if passive  will also be useful even if not to me directly  as I try to get the cheapest HW  , good work

**Pull request merged**
