### PR TITLE
Change to EUPL-1.2 License

### PR DESCRIPTION
**Pull request by softhack007**
We have agreed with the main developers of [upstream WLED](https://github.com/Aircoookie/WLED) to use EUPL-1.2 in both repositories.

This PR is to change the previous licence terms (GPLv3) of the MM-specific source code and adopt EUPL-1.2.
EUPL-1.2 is very similar to GPLv3 and applies worldwide. Unlike GPLv3, which is basically just compatible with itself, code released under EUPL-1.2 is compatible with a [well-defined list of other open source licences](https://joinup.ec.europa.eu/collection/eupl/matrix-eupl-compatible-open-source-licences).

### This PR is has two purposes:
* collect agreements of contributors who added source to WLED-MM since we moved from MIT to GPLv3 - i.e. contributions merged into `mdev` after August 2023.
* align with the licensing of [Aircoookie/WLED](https://github.com/Aircoookie/WLED), to ensure that contributions can flow in both directions without causing legal hazards.

> [!IMPORTANT]
> 
> * If you don't want your contribution to be covered by the EUPL-1.2 terms: please use this PR to make your voice heard!
> 
> * As a contributor who agrees: please approve this PR or comment with "OK".

### CODE REVIEW

**Comment by softhack007** [comment]
@Brandon502 @arneboe please inform us if you agree (could not add you as reviewers 😅 but your contributions during the last year are very important) 

@tonyxforce I remember we had a chat where you stated that its fine for you if we contribute your "party jerk" effect to upstream WLED. Nevertheless, please be invited to participate in this topic.

**Review by softhack007 — COMMENTED** [review]
OK for me, let's move to EUPL-1.2

**Review by netmindz — APPROVED** [review]

**Review by lost-hope — APPROVED** [review]
The license change is fine by me

**Comment by Brandon502** [comment]
Changing is fine with me.

**Comment by softhack007** [comment]
for comparison:

image

image

**Review by ewowi — APPROVED** [review]

**Review by ewoudwijma — APPROVED** [review]

**Comment by netmindz** [comment]
The license change is fine by me

**Comment by tonyxforce** [comment]
Fine by me

**Comment by arneboe** [comment]
Fine by me

**Comment by troyhacks** [comment]
Fine by me

**Review by troyhacks — COMMENTED** [review]
OK

**Comment by ewoudwijma** [comment]
Upstream announcement: https://github.com/Aircoookie/WLED/pull/4194

**Pull request merged**
